NhaSach2/Models/GioHang.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NhaSach2.Models
{
    public class GioHang
    {
        MyDataDataContext data = new MyDataDataContext();

        public int masach { get; set; }

        [Display(Name = "Ten Sach")]
        public string tensach { get; set; }

        [Display(Name = "Anh bia")]
        public string hinh { get; set; }

        [Display(Name = "Gia ban")]
        public Double giaban { get; set; }

        [Display(Name = "So luong")]
        public int iSoluong { get; set; }

        [Display(Name = "Thanh tien")]
        public Double dThanhtien
        {
            get { return iSoluong * giaban; }
        }

        public GioHang(int id)
        {
            masach = id;
            Sach sach = data.Saches.Single(n => n.masach == masach);
            tensach = sach.tensach;
            hinh = sach.hinh;
            giaban = double.Parse(sach.giaban.ToString());
            iSoluong = 1;
        }
    }

}

NhaSach2/Controllers/GioHangController.cs
using NhaSach2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NhaSach2.Controllers
{
    public class GioHangController : Controller

    {
        MyDataDataContext data = new MyDataDataContext();
        public List<GioHang> Laygiohang()
        {
            List<GioHang> lstGiohang = Session["Giohang"] as List<GioHang>;
            if (lstGiohang == null)
            {
                lstGiohang = new List<GioHang>();
                Session["Giohang"] = lstGiohang;
            }
            return lstGiohang;
        }

        public ActionResult ThemGioHang(int id, string strURL)
        {
            List<GioHang> lstGiohang = Laygiohang();
            GioHang sanpham = lstGiohang.Find(n => n.masach == id);
            if (sanpham == null)

            {
                sanpham = new GioHang(id);
                lstGiohang.Add(sanpham);
                return Redirect(strURL);
            }
            else
            {
                sanpham.iSoluong++;
                return Redirect(strURL);
            }
        }

        private int TongSoLuong()
        {
            int tsl = 6;

            List<GioHang> lstGiohang = Session["GioHang"] as List<GioHang>;
            if (lstGiohang != null)
            {
                tsl = lstGiohang.Sum(n => n.iSoluong);

            }
            return tsl;

        }

        private int TongSoLuongSanPham()

        {
            int tsl = 0;
            List<GioHang> lstGiohang = Session["GioHang"] as List<GioHang>;
            if (lstGiohang != null)
            {
                tsl = lstGiohang.Count;
            }
            return tsl;
        }

        private double TongTien()

        {
            double tt = 0;
            List<GioHang> lstGiohang = Session["GioHang"] as List<GioHang>;
            if (lstGiohang != null)
            {
                tt = lstGiohang.Sum(n => n.dThanhtien);
            }
            return tt;
        }

        public ActionResult GioHang()
        {
            List<GioHang> lstGiohang = Laygiohang();
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();
            ViewBag.Tongsoluongsanpham = TongSoLuongSanPham();
            return View(lstGiohang);
        }

        public ActionResult GioHangPartial()
        {
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();
            ViewBag.Tongsoluongsanpham = TongSoLuongSanPham();
            return PartialView();
        }

        public ActionResult XoaGioHang(int id)
        {
            List<GioHang> lstgiohang = Laygiohang();
            GioHang sanpham = lstgiohang.SingleOrDefault(n => n.masach == id);
            if (sanpham != null)
            {
                lstgiohang.RemoveAll(n => n.masach == id);
                return RedirectToAction("GioHang");
            }
            return RedirectToAction("GioHang");
        }

        public ActionResult CapnhatGiohang(int id, FormCollection collection)

        {
            List<GioHang> lstGiohang = Laygiohang();
            GioHang sanpham = lstGiohang.SingleOrDefault(n => n.masach == id);
            if (sanpham != null)
            {
                sanpham.iSoluong = int.Parse(collection["txtSoLg"].ToString());
            }
            return RedirectToAction("GioHang");
        }

        public ActionResult XoaTatCaGioHang()
        {
            List<GioHang> lstGiohang = Laygiohang();
            lstGiohang.Clear();
            return RedirectToAction("GioHang");
        }

        public ActionResult Index()
        {
            return View();
        }
    }

}

NhaSach2/Controllers/SachController.cs
using NhaSach2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NhaSach2.Controllers
{
    public class SachController : Controller
    {
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult ListSach()
        {
            var all_sach = from ss in data.Saches select ss;
            return View(all_sach);
        }

        public ActionResult Detail(int id)
        {
            var D_sach = data.Saches.Where(m => m.masach == id).First();
            return View(D_sach);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, Sach s)
        {
            var E_tensach = collection["tensach"];
            var E_hinh = collection["hinh"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycapnhat"]);
            var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            if (string.IsNullOrEmpty(E_tensach))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                s.tensach = E_tensach.ToString();
                s.hinh = E_hinh.ToString();
                s.giaban = E_giaban;
                s.ngaycapnhat = E_ngaycapnhat;
                s.soluongton = E_soluongton;
                data.Saches.InsertOnSubmit(s);
                data.SubmitChanges();
                return RedirectToAction("ListSach");
            }
            return this.Create();
        }
        public ActionResult Edit(int id)
        {
            var E_sach = data.Saches.First(m => m.masach == id);
            return View(E_sach);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var E_sach = data.Saches.First(m => m.masach == id);
            var E_tensach = collection["tensach"];
            var E_hinh = collection["hinh"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycatnhat"]);
            var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            E_sach.masach = id;
            if (string.IsNullOrEmpty(E_tensach))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                E_sach.tensach = E_tensach;
                E_sach.hinh = E_hinh;
                E_sach.giaban = E_giaban;
                E_sach.ngaycapnhat = E_ngaycapnhat;
                E_sach.soluongton = E_soluongton;
                UpdateModel(E_sach);
                data.SubmitChanges();
                return RedirectToAction("ListSach");
            }
            return this.Edit(id);
        }
        //-----------------------------------------
        public ActionResult Delete(int id)
        {
            var D_sach = data.Saches.First(m => m.masach == id);
            return View(D_sach);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var D_sach = data.Saches.Where(m => m.masach == id).First();
            data.Saches.DeleteOnSubmit(D_sach);
            data.SubmitChanges();
            return RedirectToAction("ListSach");
        }

        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "";
            }
            file.SaveAs(Server.MapPath("~/Content/image/" + file.FileName));
            return "/Content/image/" + file.FileName;
        }
    }
}

NhaSach2/Views/GioHang/GioHang.cshtml
@model IEnumerable<NhaSach2.Models.GioHang>

@{
    ViewBag.Title = "GioHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GioHang</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.masach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tensach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.hinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.giaban)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.iSoluong)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dThanhtien)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.tensach)
            </td>
            <td><img src="@item.hinh" width="180" alt="Alternate Text" /></td>
            @using (Html.BeginForm("Capnhatgiohang", "GioHang", new { @id = item.masach }))
            {
                <td>@String.Format("{0:0,0}", item.giaban) VND</td>
                <td><input type="number" min="1" name="txtSoLg" value="@item.iSoluong" /></td>
                <td>@Html.DisplayFor(modelItem => item.dThanhtien)</td>
                <td><a href="@Url.Action("Detail", "Sach", new { id = item.masach })">Chi tiet</a>| @Html.ActionLink("Xoa", "XoaGiohang", new { @id = item.masach })</td>
                <td><input type="submit" value="Update" class="btn btn-success" /></td>

            }
        </tr>
    }

    <tr style="font-weight:bold; text-align:left; color:red">
        <td colspan="2">So loai sach: @ViewBag.Tongsoluongsanpham</td>
        <td colspan="2">So luong sach: @ViewBag.Tongsoluong</td>
        <td colspan="4">Tong tien: @String.Format("{0:0,0}", ViewBag.Tongtien) VND</td>
    </tr>

    <tr style="font-weight:bold; color:blue; text-align:right">
        <td colspan="5">
            @Html.ActionLink("Xoa Gio Hang", "XoaTatCaGioHang")
        </td>
    </tr>
    <tr style="font-weight:bold; color:yellow; text-align:right">
        <td colspan="5">
            @Html.ActionLink("Dat hang", "Dathang", "GioHang")
        </td>
    </tr>



</table>

NhaSach2/Views/GioHang/GioHangPartial.cshtml
<a class="getstarted scrollto active" href="@Url.Action("GioHang",
"GioHang")" style="font-weight:bold; text-decoration:none">
    Giỏ hàng (@ViewBag.Tongsoluongsanpham)
</a>

NhaSach2/Views/GioHang/ThemGioHang.cshtml
@model NhaSach2.Models.GioHang

@{
    ViewBag.Title = "ThemGioHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ThemGioHang</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>GioHang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.masach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.masach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.masach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tensach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tensach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tensach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.giaban, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.giaban, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.giaban, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iSoluong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.iSoluong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.iSoluong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NhaSach2/Views/GioHang/XoaGioHang.cshtml
@model NhaSach2.Models.Sach

@{
    ViewBag.Title = "XoaGioHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>XoaGioHang</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sach</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.maloai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.maloai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tensach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tensach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.giaban)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.giaban)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngaycapnhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaycapnhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soluongton)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soluongton)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>